DROP DATABASE IF EXISTS bookshelf;
DROP DATABASE IF EXISTS bookshelf_test;
CREATE DATABASE bookshelf;
CREATE DATABASE bookshelf_test;
GRANT ALL PRIVILEGES ON DATABASE bookshelf TO postgres;
GRANT ALL PRIVILEGES ON DATABASE bookshelf_test TO postgres;
ALTER USER postgres CREATEDB;
ALTER USER postgres WITH SUPERUSER;